### ISSUE TITLE
需要azw和mobi格式的吗？

### ISSUE THREAD

**Issue by ghost** [yuanliangding/books#13]
需要的话我整理下，你留个邮箱。个人建议看书用kindle，还有一点觉得书不错买一本实体书，赞助哈原作者。

**Comment by Franklyn1987** [comment]
baiyuexingchen@gmail.com

**Comment by yuanliangding** [comment]
yuanliangding@126.com谢谢。我没在电脑前，都是用kindle看的。不错的书，也是会买实体的。一是对原作者的感谢，二是收藏或者随手翻阅方便。

**Comment by guoxiaoxu** [comment]
https://drive.google.com/drive/folders/1_uzn49DRhdsML6sS5pkzFrj_Eu15YjSb?usp=sharing   直接在这里共享了，请勿删除文件，其他人也是。发送邮件太慢。

**Comment by guoxiaoxu** [comment]
## 声明

- 1、版权归作者所有，任何用于商业目的的自己负责。
- 2、请尊重原作者的劳动成果，感觉书写的不错。买本实体书
- 3、可以到这里[集思会][1]下载你需要的，直接推到Kindle

[1]:http://www.kindlepush.com/main

**Comment by guoxiaoxu** [comment]
也可以把邮箱添加到Amazon里面，在集思会添加自己的kindle邮箱。不能推送的手动下载下来直接放到kindle安装目录里。

**Comment by Louis-udm** [comment]
先感谢，下了几本。但是mobi和azw3是什么鬼？用什么打开？

**Comment by ghost** [comment]
@Louis-udm AZW3值亚马逊在kindle上专用的，采用加密。mobi不是加密的。就是你直接可以在文字上做笔记，勾画重点。安装kindle，把AZW3和mobi文件直接放在目录下就可以。还有一种就是推送的方式，把你自己喜欢的文章推送到kindle上。PC和移动端是共享的。 注册时每个端都分配一个专用邮箱，你自己也可以发送内容。或者RSS订阅你自己喜欢的内容。
![213_134059](https://user-images.githubusercontent.com/26244337/36135083-b21e3424-10c3-11e8-9df6-3c6d5916f065.jpg)
![snipaste_20180213_133539](https://user-images.githubusercontent.com/26244337/36135134-2e0fcff2-10c4-11e8-83a4-5333f83dbfc2.jpg)

**Comment by Louis-udm** [comment]
没有kindle怎么办？有一两本我下的，只有mobi版本

**Comment by guoxiaoxu** [comment]
@Louis-udm 下载安装。

**Comment by yuanliangding** [comment]
感谢了。可以留个微信或者QQ。哈

**Comment by guoxiaoxu** [comment]
@yuanliangding  QQ不用了，微信也卸载安装到另外一个不咋用的手机了。可以关注我的Twitter@Guo_1_9

**Comment by guoxiaoxu** [comment]
http://www.mebook.cc/ 我的小书屋。这个站点太给力了
